# Generated by Django 4.0.5 on 2023-04-08 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_jobportal_is_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobportal',
            name='posted_by',
        ),
    ]
